### ISSUE TITLE
After v3.0.62 MQTT no longer connects

### ISSUE THREAD

**Issue by danielstevenberger** [sst/ion#1011] opened 2024-09-07 17:02 UTC
After updating past v3.0.62 my MQTT connections no longer connect using a setup following the Realtime example. 
When downgrading to v3.0.61 I no longer experience the issue.

Is principalId required now when using Realtime?
Should the same connection before still be working?
Are there any new additional changes needed?

```
  return client.new_connection(
    iot.AwsIotMqttConnectionConfigBuilder.new_with_websockets()
      .with_clean_session(true)
      .with_client_id(`client_${id}`)
      .with_endpoint(endpoint)
      .with_custom_authorizer("", authorizer, "", token || "")
      .build()
  )
  ```

**Comment by danielfyhr** [comment] 2024-09-09 16:41
in v3.0.62 the principalId in the returned PolicyDocument was from changed `Date.now().toString()` (`="1725899184669"`) to `evt.protocolData.mqtt?.username` which evaluates to values like
```
?x-amz-customauthorizer-name=realtime-project-danielfy-RealtimeProjectRealti
meAuthorizer&SDK=NodeJSv2&Version=1.21.8
```
which is not a valid for principalId, see below.

https://github.com/sst/ion/pull/900/files#diff-7900b324c128a2581ca9421cee4c79284916691be602b0eb184b786c95db405dR116

> principalId: An alphanumeric string that acts as an identifier for the token sent by the custom authorization request. The value must be an alphanumeric string with at least one, and no more than 128, characters and match this regular expression (regex) pattern: ([a-zA-Z0-9]){1,128}. Special characters that are not alphanumeric are not allowed for use with the principalId in AWS IoT Core. Refer to the documentation for other AWS services if non-alphanumeric special characters are allowed for the principalId.

[source](https://docs.aws.amazon.com/iot/latest/developerguide/config-custom-auth.html?fbclid=IwZXh0bgNhZW0CMTEAAR2o4zkQ4LEA5vyG7Y6uMsM_APAkv8RrlKPreAkhz9DNQ3e9tzFSTAEuSWQ_aem_PKZxO3NIAKwV8M6_mHVlog#custom-auth-lambda)

In #899 it was added to enhance authentication in realtime
but it seems you cant use `evt.protocolData.mqtt?.username` directly as a principalId.

**Comment by danielstevenberger** [comment] 2024-09-15 01:44
Any updates on getting the fixed merge?

**Comment by fwang** [comment] 2024-09-19 21:26
Hey @danielstevenberger the PR was merged a while back.

Feel free to reopen if the issue is not fixed in the latest version.

**Comment by danielfyhr** [comment] 2024-09-21 11:47
@fwang This is not fixed. I don't see anything that was merged to fix this issue.

**Comment by danielstevenberger** [comment] 2024-09-21 16:10
@fwang im not having the issue in the latest version. I've also switched to following the new example in the documentation.

**Comment by danielfyhr** [comment] 2024-09-21 18:27
@danielstevenberger 

When following the example in the documentation, do you set principalId?

**Comment by danielfyhr** [comment] 2024-10-03 12:00
@fwang ok i found the cause of this... In the updated [docs](https://github.com/sst/ion/blob/91848b82a3399ad5b322a5840f52ce5c0141730b/www/src/content/docs/docs/start/aws/realtime.mdx#4-create-a-connection) the mqtt connection is created differently as compared to the issue description.

when using this 
```javascript
  return mqtt.connect(`wss://${endpoint}/mqtt?x-amz-customauthorizer-name=${authorizer}`, {
    protocolVersion: 5,
    manualConnect: true,
    username: "", // Must be empty for the authorizer
    password: "PLACEHOLDER_TOKEN", // Passed as the token to the authorizer
    clientId: `client_${window.crypto.randomUUID()}`,
  });
```

the generated principleId works - although i'm not sure why the docs say username "Must be empty for the authorizer"

you can close this issue i think :)

**Comment by jayair** [comment] 2024-10-04 19:34
From what I remember, you need the username only if you are using the auth.

**Closed** 2024-10-04 19:35 UTC
