### ISSUE TITLE
Ran "sst init --verbose" on mac m1 chip.

### ISSUE THREAD

**Issue by richard-aoede** [sst/ion#79] opened 2024-03-26 22:31 UTC
```
time=2024-03-26T16:26:37.452-05:00 level=INFO msg="copying template" path=templates/nextjs/files/sst-env.d.ts
time=2024-03-26T16:26:37.453-05:00 level=INFO msg="copying template" path=templates/nextjs/files/sst.config.ts
time=2024-03-26T16:26:37.453-05:00 level=INFO msg=patching file=tsconfig.json
time=2024-03-26T16:26:37.454-05:00 level=ERROR msg="exited with error" err="invalid state detected\ngithub.com/evanphx/json-patch/v5.init\n\t<autogenerated>:1\nruntime.doInit1\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/proc.go:7176\nruntime.doInit\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/proc.go:7143\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/proc.go:253\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/asm_arm64.s:1222"
×  Unexpected error occurred. Please check the logs or run with --verbose for more details.
```

For context, I'm using Prisma in my project. I'm thinking Prisma has separate engine that crashes SST. I've dealt with it on the older version of SST.

Note this line:
```\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/asm_arm64.s:1222```

**Comment by richard-aoede** [comment] 2024-03-26 22:34
I have this on prisma client. Still errors out. Here's some [Prisma docs](https://www.prisma.io/docs/orm/prisma-client/deployment/serverless/deploy-to-aws-lambda) as well
```
generator client { 
    provider = "prisma-client-js"
    binaryTargets = ["native", "linux-arm64-openssl-1.0.x"] 
}
```

**Comment by jayair** [comment] 2024-03-26 23:21
Hmm I think it's trying to create the template and failing. Can you share the tsconfig?

**Comment by richard-aoede** [comment] 2024-03-27 04:05
//ts.config

{
  "compilerOptions": {
    /* Base Options: */
    "esModuleInterop": true,
    "skipLibCheck": true,
    "target": "es2022",
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "force",
    "isolatedModules": true,

    /* Strictness */
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "checkJs": true,

    /* Bundled projects */
    "lib": ["dom", "dom.iterable", "ES2022"],
    "noEmit": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "jsx": "preserve",
    "plugins": [{ "name": "next" }],
    "incremental": true,

    /* Path Aliases */
    "baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"]
    }
  },
  "include": [
    ".eslintrc.cjs",
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "**/*.cjs",
    "**/*.js",
    ".next/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}

**Comment by thdxr** [comment] 2024-03-27 12:32
the the issue is #85 will close this and track there

**Closed** 2024-03-27 12:33 UTC

**Comment by richard523** [comment] 2024-04-22 19:43
https://github.com/richard523/sst-ion-test


Feel free to contact me on either account. I was original poster here: https://github.com/sst/ion/issues/79

Still errors out but produces slightly different output. I found out it's not Prisma.

`richardgatchalian@Richards-MacBook-Air sst-ion-test % sst deploy --verbose
time=2024-04-22T14:17:20.823-05:00 level=INFO msg="checking for pulumi" path="/Users/richardgatchalian/Library/Application Support/sst/bin/pulumi"
time=2024-04-22T14:17:20.993-05:00 level=INFO msg="checking for bun" path="/Users/richardgatchalian/Library/Application Support/sst/bin/bun"
time=2024-04-22T14:17:20.999-05:00 level=INFO msg="initializing project" version=0.0.298
time=2024-04-22T14:17:20.999-05:00 level=INFO msg="esbuild building"
time=2024-04-22T14:17:21.002-05:00 level=INFO msg="esbuild built" outfile=/System/Volumes/Data/Users/richardgatchalian/Documents/GitHub/Kali-Fix/sst-ion/sst-ion-test/.sst/eval/eval-1713813440999.mjs
time=2024-04-22T14:17:21.002-05:00 level=INFO msg="evaluating config"
time=2024-04-22T14:17:21.044-05:00 level=INFO msg="config evaluated"
time=2024-04-22T14:17:21.044-05:00 level=ERROR msg="exited with error" err="Error evaluating config: exit status 1\nfile:///System/Volumes/Data/Users/richardgatchalian/Documents/GitHub/Kali-Fix/sst-ion/sst-ion-test/.sst/eval/eval-1713813440999.mjs:14\nvar bucket = new sst.aws.Bucket(\"IonBucketTest\", {\n             ^\n\nReferenceError: sst is not defined\n    at file:///System/Volumes/Data/Users/richardgatchalian/Documents/GitHub/Kali-Fix/sst-ion/sst-ion-test/.sst/eval/eval-1713813440999.mjs:14:14\n    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)\n    at async loadESM (node:internal/process/esm_loader:28:7)\n    at async handleMainPromise (node:internal/modules/run_main:113:12)\n\nNode.js v20.12.0\n"
×  Unexpected error occurred. Please check the logs or run with --verbose for more details.`

**Comment by zohaibakber** [comment] 2024-04-23 16:03
@richard523 show your tsconfig and where is this project initialized at can you share details?

**Comment by richard523** [comment] 2024-04-23 16:11
Apologies, I was messing with imports trying to get it to work. Same error as issue/79. Notice I removed the uneccessary import trying to get it to work. 

https://github.com/richard523/sst-ion-test/blob/main/sst.config.ts

`richardgatchalian@Richards-MacBook-Air sst-ion-test % sst deploy --verbose time=2024-04-22T14:17:20.823-05:00 level=INFO msg="checking for pulumi" path="/Users/richardgatchalian/Library/Application Support/sst/bin/pulumi" time=2024-04-22T14:17:20.993-05:00 level=INFO msg="checking for bun" path="/Users/richardgatchalian/Library/Application Support/sst/bin/bun" time=2024-04-22T14:17:20.999-05:00 level=INFO msg="initializing project" version=0.0.298 time=2024-04-22T14:17:20.999-05:00 level=INFO msg="esbuild building" time=2024-04-22T14:17:21.002-05:00 level=INFO msg="esbuild built" outfile=/System/Volumes/Data/Users/richardgatchalian/Documents/GitHub/Kali-Fix/sst-ion/sst-ion-test/.sst/eval/eval-1713813440999.mjs time=2024-04-22T14:17:21.002-05:00 level=INFO msg="evaluating config" time=2024-04-22T14:17:21.044-05:00 level=INFO msg="config evaluated" time=2024-04-22T14:17:21.044-05:00 level=ERROR msg="exited with error" err="Error evaluating config: exit status 1\nfile:///System/Volumes/Data/Users/richardgatchalian/Documents/GitHub/Kali-Fix/sst-ion/sst-ion-test/.sst/eval/eval-1713813440999.mjs:14\nvar bucket = new sst.aws.Bucket(\"IonBucketTest\", {\n             ^\n\nReferenceError: sst is not defined\n    at file:///System/Volumes/Data/Users/richardgatchalian/Documents/GitHub/Kali-Fix/sst-ion/sst-ion-test/.sst/eval/eval-1713813440999.mjs:14:14\n    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)\n    at async loadESM (node:internal/process/esm_loader:28:7)\n    at async handleMainPromise (node:internal/modules/run_main:113:12)\n\nNode.js v20.12.0\n" ×  Unexpected error occurred. Please check the logs or run with --verbose for more details.`
