### ISSUE TITLE
Adding VPC Configuration Throws 504 Error The Request Could Not Be Satisfied

### ISSUE THREAD

**Issue by shahbhavik01** [sst/ion#571] opened 2024-06-17 13:16 UTC
I'm deploying my NextJS app to AWS. This is my config:

```
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "oneact-landing-page",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
      providers: {
        aws: {
          region: "us-east-1",
        },
      },
    };
  },
  async run() {
    new sst.aws.Nextjs("MyWeb", {
    vpc: {
          securityGroups: ["sg-123456"], 
          subnets: [
            "subnet-123456",
            "subnet-1234567",
          ],
        },
    });
  },
});
```

When I remove the VPC Config, the deployment works well. When I add the VPC config, the website starts throwing the following error:

![image](https://github.com/sst/ion/assets/13501832/08fece56-c541-4a41-8ef8-3575b960698d)

For now, the security group is allowing all inbound and outbound access. The subnets are also both public subnets with Internet Gateway and NAT Gateways available. I have triple checked that VPC configuration. Any idea what can be causing this? 

Also, any documentation around what ports should be allowed in the Security Group to allow for NextJS traffic would be really helpful.

**Comment by mikexavier** [comment] 2024-06-17 13:59
I'm seeing the same when setting the vpc config in a Nextjs component.

I was losing my mind for the past week trying to figure out where I was going wrong with my vpc set-up (it could still be incorrect 🤫).

In my case, I am setting up an `aws.rds.Instance` postgres database, initially in a private subnet allowing incoming traffic from a public subnet, and then adding the public subnet to the Nextjs component. I wanted a set-up where the Nextjs application (a [Payload CMS](https://github.com/payloadcms/payload-3.0-demo/)) could access the database, but the database wasn't publicly accessible.

I've tried a few combinations, simplified it to public subnets only for testing and opened it up allowing all traffic from everywhere. No dice.

<details>
<summary>My vpc/databse/nextjs set-up</summary>

```typescript
const vpc = new aws.ec2.Vpc(`SaanaCmsVpc${stage}`, {
  cidrBlock: "10.0.0.0/16",
  enableDnsHostnames: true,
  enableDnsSupport: true,
});

const publicSubnet1 = new aws.ec2.Subnet(`SaanaSubnetPublic1${stage}`, {
  vpcId: vpc.id,
  cidrBlock: "10.0.1.0/24",
  mapPublicIpOnLaunch: true,
  availabilityZone: "eu-central-1a",
});

const publicSubnet2 = new aws.ec2.Subnet(`SaanaSubnetPublic2${stage}`, {
  vpcId: vpc.id,
  cidrBlock: "10.0.2.0/24",
  mapPublicIpOnLaunch: true,
  availabilityZone: "eu-central-1b",
});

const dbSecurityGroup = new aws.ec2.SecurityGroup(
  `SaanaDbSecurityGroup${stage}`,
  {
    vpcId: vpc.id,
    ingress: [
      {
        protocol: "tcp",
        fromPort: 5432,
        toPort: 5432,
        cidrBlocks: ["0.0.0.0/0"],
      },
    ],
    egress: [
      {
        protocol: "-1",
        fromPort: 0,
        toPort: 0,
        cidrBlocks: ["0.0.0.0/0"],
      },
    ],
  }
);

const dbSubnetGroup = new aws.rds.SubnetGroup(`SaanaCmsDbSubnetGroup${stage}`, {
  name: `saana-db-subnet-group-${stage}`,
  subnetIds: [publicSubnet1.id, publicSubnet2.id],
});

const internetGateway = new aws.ec2.InternetGateway(
  `SaanaCmsInternetGateway${stage}`,
  {
    vpcId: vpc.id,
  }
);

const publicRouteTable = new aws.ec2.RouteTable(
  `SaanaCmsPublicRouteTable${stage}`,
  {
    vpcId: vpc.id,
    routes: [
      {
        cidrBlock: "0.0.0.0/0",
        gatewayId: internetGateway.id,
      },
    ],
  }
);

const publicRouteTableAssociation1 = new aws.ec2.RouteTableAssociation(
  `SaanaCmsPublicRouteTableAssociation1${stage}`,
  {
    subnetId: publicSubnet1.id,
    routeTableId: publicRouteTable.id,
  }
);

const publicRouteTableAssociation2 = new aws.ec2.RouteTableAssociation(
  `SaanaCmsPublicRouteTableAssociation2${stage}`,
  {
    subnetId: publicSubnet2.id,
    routeTableId: publicRouteTable.id,
  }
);

export const db = new aws.rds.Instance(`SaanaCmsPostgresDb${stage}`, {
  identifier: `saana-cms-postgres-db-${stage}`,
  engine: "postgres",
  engineVersion: "16.2",
  instanceClass: "db.t3.micro",
  allocatedStorage: 20,
  dbName: `cmsPostgresDb${stage}`,
  username: `saanaCmsDb${stage}`,
  password: rdsPassword.value,
  storageType: "gp2",
  vpcSecurityGroupIds: [dbSecurityGroup.id],
  dbSubnetGroupName: dbSubnetGroup.name,
  skipFinalSnapshot: true,
  publiclyAccessible: isDev,
  deletionProtection: isProduction,
});

let cms;
CmsDbConnectionString.apply((connectionString) => {
  cms = new sst.aws.Nextjs("SaanaCMS", {
    path: "packages/cms",

    vpc: {
      securityGroups: [cmsSecurityGroupId],
      subnets: [publicSubnetId1, publicSubnetId2],
    },

    domain: {
      name: domain,
      dns: sst.aws.dns({
        zone: zoneId,
      }),
    },

    environment: {
      NEXT_PUBLIC_CMS_MEDIA_S3_REGION: CmsMediaS3Region,
      NEXT_PUBLIC_CMS_MEDIA_S3_ENDPOINT: CmsMediaS3EndPoint,
      RDS_POSTGRES_DB_CONNECTION_STRING: connectionString,
    },

    link: [
      CmsBucket,
      CmsMediaS3AccessKeyId,
      CmsMediaS3SecretAccessKey,
      PayloadSecret,
      SupabaseConnectionString,
    ],
  });
});

export { cms };

```  

---

I was kinda hoping by copy/pasting all that, I'd notice something... but I'm blind at this point.

I've logged all variables and secret, all seem correct and passed in as expected

</details>

**Comment by shahbhavik01** [comment] 2024-06-18 10:50
Also, any documentation around what ports should be allowed in the Security Group to allow for NextJS traffic would be really helpful.

**Comment by mikexavier** [comment] 2024-07-08 23:51
Hey @shahbhavik01 @victor-landa did you manage to get this working somehow? 

@fwang this is a bit of a blocker for me. It would be great to know if it's a skill issue or something on the SST side.

Cheers!

**Comment by jayair** [comment] 2024-07-13 00:30
I'll check

**Comment by fwang** [comment] 2024-07-30 16:59
@shahbhavik01 @mikexavier @victor-landa hmm i'm not able to reproduce the issue. Here's the test repo i used - https://github.com/fwang/triage-nextjs-vpc

**Comment by fwang** [comment] 2024-07-30 17:00
Also do all routes result in the error page? Or only ssr or static asset routes?

**Comment by mikexavier** [comment] 2024-08-15 17:56
Hey @fwang I noticed you used a public bucket in the example. Is it the same config for private?

I might be missing how to set it up correctly. In my case, I'd like to access a private db from a Nextjs CMS. I dropped how I was going about it above. Can you see where I might be slipping up? 

Thx!

**Comment by mikexavier** [comment] 2024-08-24 11:27
@fwang I'm still battling this one... 🤨

If I have

```
const vpc = new sst.aws.Vpc("MyVpc");

const cmsDb = new aws.rds.Instance("CmsDb", {
  publiclyAccessible: false,
  ...
});

new sst.aws.Nextjs("CMS", {
    link: [cmsDb],
    vpc: {
      securityGroups: vpc.securityGroups,
      privateSubnets: vpc.privateSubnets,
    },
...
```

My understanding is that as per the [docs](https://sst.dev/docs/component/aws/nextjs/#vpc) it configures the server function for the Next.js app to use this VPC config.

If I go to Lambda > Functions > dev-CMSDevServerFunction > Configuration > VPC I should be able to see the vpc settings from "MyVpc" right? 

I see
```
No VPC configuration
This function isn't connected to a VPC.
```

What am I missing?
🙏🏼

**Comment by danielstevenberger** [comment] 2024-09-08 07:26
Any updates? Facing same issue on all pages.

**Comment by zluo01** [comment] 2024-09-09 05:04
Also getting the same issue when do simply config like following, no extra aws resource, simply adding vpc fails with the 504.

```
export default $config({
  app() {
    return {
      name: 'test',
      removal: 'remove',
      home: 'aws',
      providers: {
        aws: {
          region: 'us-east-2',
        },
      },
    };
  },
  async run() {
    new sst.aws.Nextjs('test', {
      domain: { name: 'test.com', redirects: ['www.test.com'] },
      environment: {
       ...
      },
      imageOptimization: {
        memory: '256 MB',
      },
      server: {
        memory: '256 MB',
        architecture: 'arm64',
      },
      vpc: {
        privateSubnets: [...],
        securityGroups: [...]
      }
    });
  },
});
```

**Comment by zluo01** [comment] 2024-09-15 05:15
Hi @fwang, reprouction repo that have the problem.


repo https://github.com/zluo01/nextjs-sst-vpc.

**Comment by fwang** [comment] 2024-09-19 21:18
VPC needs to have NAT enabled otherwise Lambda functions do not have internet connection.

```ts
const vpc = new sst.aws.Vpc('testVpc', {
  nat: "managed"
});
```

Also you can just pass `vpc` directly without spreading it:
```ts
new sst.aws.Nextjs('test', {
  ...,
  vpc
});
```

Lemme know if that works.

**Comment by zluo01** [comment] 2024-09-20 02:24
@fwang,  I believe the use case here is want to have lambda access aws internal resource within private subnets, not internet resources.  Why do we need to have nat enabled ?

**Comment by mikexavier** [comment] 2024-09-20 14:23
Adding NAT made everything work as expected for me. In the end, I set everything up from scratch to use [fck-nat](https://fck-nat.dev/stable/) though, to save some costs for now.

**Comment by fwang** [comment] 2024-09-20 15:03
@mikexavier oh nice.. did u set it in code? ie. something similar to this https://github.com/sst/ion/issues/815#issuecomment-2358599346

**Comment by mikexavier** [comment] 2024-09-20 15:46
yes, looks like

```
const vpc = new aws.ec2.Vpc(`vpc${STAGE}`, {
  cidrBlock: "10.0.0.0/16",
  enableDnsSupport: true,
  enableDnsHostnames: true,
});

const publicSubnet = new aws.ec2.Subnet(`publicSubnet${STAGE}`, {
  vpcId: vpc.id,
  cidrBlock: "10.0.1.0/24",
  mapPublicIpOnLaunch: true,
  availabilityZone: `${AWS_REGION}a`,
});

const natSecurityGroup = new aws.ec2.SecurityGroup(`natSecurityGroup${STAGE}`, {
  vpcId: vpc.id,
  ingress: [
    {
      cidrBlocks: [
        // relevant subnets
      ],
      protocol: "-1",
      fromPort: 0,
      toPort: 0,
    },
  ],
  egress: [
    {
      cidrBlocks: ["0.0.0.0/0"],
      protocol: "-1",
      fromPort: 0,
      toPort: 0,
    },
  ],
});

const networkInterface = new aws.ec2.NetworkInterface("natInterface", {
  subnetId: publicSubnet.id,
  securityGroups: [natSecurityGroup.id],
});

const ami = await aws.ec2.getAmi({
  filters: [
    { name: "name", values: ["fck-nat-al2023-*"] },
    { name: "architecture", values: ["arm64"] },
  ],
  owners: ["568608671756"],
  mostRecent: true,
});

const natInstance = new aws.ec2.Instance(`fck-nat-instance-${STAGE}`, {
  ami: ami.id,
  instanceType: "t4g.nano",
  networkInterfaces: [
    {
      networkInterfaceId: networkInterface.id,
      deviceIndex: 0,
    },
  ],
  userData: `#!/bin/bash
  echo "fck-nat configuration" > /etc/fck-nat.conf
  service fck-nat restart`,
});
```

I wish I had used SST's VPC component as I've now been setting up a bastion host, and noticed you have a 
 [bastion](https://sst.dev/docs/component/aws/vpc/#bastion) option ... that'll be a fun session, moving everything.
 
 I also get an issue with some services not being deleted on `sst remove` but haven't looked into that yet.

**Comment by fwang** [comment] 2024-09-20 17:43
@mikexavier Thanks of sharing.. VPC will likely soon support fknat.

> I also get an issue with some services not being deleted on `sst remove` but haven't looked into that yet.
Feel free to open an issue if u get a chance to look into it.

**Comment by fwang** [comment] 2024-09-20 17:43
Closing this issue was the culprit being NAT not enabled in VPC

**Closed by fwang** 2024-09-20 17:43 UTC
